# Generated by Django 5.0.4 on 2024-04-23 12:46

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_group_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='private-chat', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
