name: Build Docker
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/guilhermewolf/chatify:latest
